kind: Secret
apiVersion: v3
metadata:
  name: greenanimals.env
  namespace: default
type: Opaque
data:
  #/greenanimals/incoming
  MATTERMOST_ENDPOINT: L2dyZWVuYW5pbWFscy9pbmNvbWluZw==
  #http://192.168.10.212:8796/hooks/4h173jnun3yj3drw37wn3dkeqh
  MATTERMOST_INCOME_URL: aHR0cDovLzE5Mi4xNjguMTAuMjEyOjg3OTYvaG9va3MvNGgxNzNqbnVuM3lqM2RydzM3d24zZGtlcWg=
    #a123jvqsiupgp666t5ck9ug3h3a
  MATTERMOST_TOKEN: YTEyM2p2cXNpdXBncDY2NnQ1Y2s5dWczaDNh
    #greenerbot
  MATTERMOST_GREENERBOT_USERNAME: Z3JlZW5lcmJvdA==
    #redis://192.168.10.212:26379/greenerbot
  REDIS_URL: cmVkaXM6Ly8xOTIuMTY4LjEwLjIxMjoyNjM3OS9ncmVlbmVyYm90
    #https://s3-eu-west-1.amazonaws.com/greenerbot/ravenclaw.png
  MATTERMOST_ICON_URL: aHR0cHM6Ly9zMy1ldS13ZXN0LTEuYW1hem9uYXdzLmNvbS9ncmVlbmVyYm90L3JhdmVuY2xhdy5wbmc=
  GREENERBOT_JENKINS_URL:
  GREENERBOT_JENKINS_AUTH:
