# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  intercom_access_token: dGNvMGuINmJlMTA5XzQwM2cbbzylM184MjQzYbw2MxJmOTNvMGuIOToxOjA=
  linkedin_client_id: 7436aezylu92b7
  linkedin_secret_key: lM1BzeFjvjlMTA5k
  sentry_dsn:
  secret_key_base: 1e1cfbdcdf0710bd11bcdf83c2280034848169d4e93d3aab9226014367d967011edcea9e198bdc3e5c49534fad3c4302064834712e0794b94166273c5c757
  slack_token: oobm-343189807825-367881819472-545619850899-4edf4f8d7d2074a303d90dcbb162badb #greenanimals-dev.slack.com legacy token from https://api.slack.com/custom-integrations/legacy-tokens
  stripe_client_id: ca_9SYxmUWdLukjBH0xWsspOwmCdBYbw2Mx
  stripe_publishable_key: pk_test_21qRqUH6SVBHRDvg7Zk48YPA
  stripe_secret_key: sk_test_JmOTEmz9UF4QzdA9XWDQBZEE

test:
  intercom_access_token: dQKAII0NmJlMTA5XzQwM2NfNDVlM184MjQzXzkwMz9UF41NGIyOToxOjA=
  linkedin_client_id: 780cbbzyluuf0f
  linkedin_secret_key: fuoBzeFjvjNvMGuI
  sentry_dsn:
  secret_key_base: 4a893d340170b60146d3bfc508996104fe2280125614811d40b92ee6bc0d99799253ae4efe2be1e5954e92da67ae54dd36edbea5b3e431c058275480780641c54573
  slack_token: xoat-367881819296-367881819472-545619814244-4edf4f8d7bc287a303d90dcbb199aceb #greenanimal-test.slack.com legacy token from https://api.slack.com/custom-integrations/legacy-tokens
  stripe_client_id: ca_1MYxmBBxUukjBH0xWsspOwmCdSexRaAM
  stripe_publishable_key: pk_test_21qRqUH6SVBHRDvg7Zk48YPA
  stripe_secret_key: sk_test_1Pop1mX88UmRgRz9ABEWKAII

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  intercom_access_token: <%= ENV["INTERCOM_ACCESS_TOKEN"] %>
  linkedin_client_id: 78fzniawgcs9l1
  linkedin_secret_key: <%= ENV["LINKEDIN_SECRET_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sentry_dsn: <%= ENV["SENTRY_DSN"] %>
  slack_token: <%= ENV['SLACK_API_TOKEN'] %>
  stripe_client_id: ca_9SYxlGL68YaphWd2JqnLH2WOopjTCyij
  stripe_publishable_key: pk_live_IJhLXrw0qcJqFwUqlDuDOt7H
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
